### ISSUE TITLE
Can Prism create ful UI layouts in XML ?

### ISSUE THREAD

**Issue by Zeyad-37** [GettEngineering/Prism#18]
I am wondering if Prism can download full screen and convert them into xml ? Or could you point to where can I find it in the docs? Thanks :)

**Comment by freak4pc** [comment]
Hey Zeyad :) 
Thanks for your message ! 

Prism isn’t built to do what you’re asking for right now, and it’s not very realistic it will anytime soon since it’s not part of the current roadmap.

Prism’s main goal is to allow synchronization of design details, such as Colors, Text Style and Spacing – using Zeplin as the design scourge of truth and generating that code for all platform.

An interesting next step would be the ability to allow generating components from Zeplin, but generating entire screens is currently out of scope for the project. 

If you want to learn more about Prism, check out the **Documentetion** and **Examples*** folders , as well as the short intro video on the top of the README. 

Hope this helps to clarify things up!


Shai
