### ISSUE TITLE
textStyle.fontSize does not roundedToNearest

### ISSUE THREAD

**Issue by gdelmas** [GettEngineering/Prism#28]
I notices some tokens output floats, where others seem to look like integer.

- `textStyle.fontSize` gives a float
- where `textStyle.lineHeight` appears to be an integer

in some emitted languages one or the other might not be desirable, or will have to be specified. On further inspection i than noticed that [roundToNearest](https://github.com/GettEngineering/Prism/blob/master/Sources/PrismCore/TemplateParser/TemplateParser%2BToken.swift#L205) always produces a float. So i assume that by not having any decimal places, it did not appear as one in the emit. This is already quite ideal for languages that don't need that `.` to specify the type.

Would it be possible for `fontSize` to be consistent with that rounding? Or do you think different emits would be needed.

I see that it would be nice to keep it rather simple.

Thanks for creating this great project.

**Comment by freak4pc** [comment]
Hey @gdelmas - 
`roundToNearest` is useful for things like line height, where you'd often get "1.3291" or weird values like that, in which case we round to the two closest digits.

So in reality it could be _either_:
- An int, if the value was `1.003`, it would be `1.00` which will be emitted as `1`
- A float if the value has something in those two precision points (e.g. `1.3291` -> `1.33`)

I'm not sure this logic fits `fontSize` because:
1. Font sizes are usually whole - I'm not too sure why in your case you get float font sizes but that might be something to look into from the design side
2. Rounding a font size might product an entirely different thing than you expect. 

Maybe if you can explain your use-case I can try to help. Perhaps a transformer (e.g. `textStyle.fontSize|roundUp`) could help

**Comment by gdelmas** [comment]
I completely agree with you. The issue I am seeing is that `{{% textStyle.fontSize %}}` emits `12.0`, where i was expecting `12`. This would solve my current need.

Apart from that i was thinking ahead, as if some other consumer would need one of the following emits:
- `12.0`
- `12,0`
- `12`

Maybe for that kind of a `format`er transformation, like `String(format: ...)` would help.

Out of curiosity, what is the reason to have `identity.camelcase` and `identity.snakecase` when there are transforms? Is it for backwards compatibility? I find the transforms much more sensible.

**Comment by freak4pc** [comment]
I think formatting might be a bit out-of-scope for this repo since in most programming languages 12.0 and 12 have an identical. JSON specifically has 12 meaning `Int` or `Float` and 12.0 meaning `Float`. 

I think it would help me better to understand what's the use case you have for this, so I can figure out a holistic solution or it :) 

> Out of curiosity, what is the reason to have identity.camelcase and identity.snakecase when there are transforms? Is it for backwards compatibility? I find the transforms much more sensible.

Not realy for backwards compatibility since we're on 0.x anyways, but in general I had the same though. 

It is mainly because the casing thing is specific to Asset Identities and is not generalized for other use-cases, though it could be. I think it would help again trying to see if there's a proper use-case for this: 

https://github.com/GettEngineering/Prism/blob/master/Sources/PrismCore/Models/AssetIdentity.swift#L28-L45

**Comment by gdelmas** [comment]
the use case would be CSS, where you ideally would want to see `12px` as font size, without a decimal place.

> It is mainly because the casing thing is specific to Asset Identities and is not generalized for other use-cases, though it could be. I think it would help again trying to see if there's a proper use-case for this:

I now understand that there is some `words` splitting going on before. I think there is no special use case, that would make it necessary. It might just be simpler to understand.

Basically:
`{{% color.identity.snakecase %}}`
vs
`{{% color.identity|snakecase %}}`

This becomes more apparent when contemplating this example, where I was trying to get kebap-case:
`{{% color.identity.snakecase|replace(_,-) %}}`

**Comment by freak4pc** [comment]
> the use case would be CSS, where you ideally would want to see 12px as font size, without a decimal place.

I don't think it should be a problem specializing for whole numbers and dropping post the decimal point, but just to be clear this is purely aesthetic as CSS should have no problem dealing with decimals.

**Comment by freak4pc** [comment]
And about this: 

> {{% color.identity|snakecase %}}

I understand what you're saying - but, making something like this a transformation means it has to work on _any_ kind of input which would require probably much more testing, and more importantly, a valid use case (because there's no real need developing something that's not gonna be used :P) 

Instead, we treat it as a property of the identity itself since its only specific to it. I think that right now, it makes most sense considering everything. 

And about this:
> {{% color.identity.snakecase|replace(_,-) %}}

I think kebab-case and PascalCase are two very valid additions to add into Prism identities in general, so maybe that should be the direction.

**Comment by freak4pc** [comment]
I've added kebab and pascal identities in #32

**Comment by gdelmas** [comment]
you are right. thanks for all the work.
